Repository eclipse/transformer, pull requests merged in 2020-06, with the labels that each got.

#29 22 - Incorrect sub-package transformation
  transformer/src/main/java/org/eclipse/transformer/action/impl/SignatureRuleImpl.java
Labels: bug

#32 31 Extend transformer public API to expose the change information
  transformer/src/main/java/org/eclipse/transformer/Transformer.java
Labels: enhancement

#33 10 Extend XML file selection pattern to additional file extensions
  transformer/.settings/org.eclipse.jdt.ui.prefs
  transformer/build.gradle
  transformer/src/main/java/org/eclipse/transformer/Transformer.java
  transformer/src/main/java/org/eclipse/transformer/action/ActionType.java
  transformer/src/main/java/org/eclipse/transformer/action/impl/SignatureRuleImpl.java
  transformer/src/main/java/org/eclipse/transformer/action/impl/TextActionImpl.java
  transformer/src/main/java/org/eclipse/transformer/action/impl/XmlActionImpl.java
  transformer/src/main/java/org/eclipse/transformer/jakarta/JakartaTransformer.java
  transformer/src/main/resources/org/eclipse/transformer/build.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-bundles.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-direct.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-renames.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-servletVersion.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-text-master.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-transactionManager.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-transactionSynchronizationRegistry.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-userTransaction.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-versions.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-xml-all.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-xml-dd.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-xml-server.properties
  transformer/src/main/resources/org/eclipse/transformer/jakarta/jakarta-xml-web.properties
  transformer/src/test/java/transformer/test/TestTransformXML.java
Labels: enhancement

#62 61 Fix issue where service loader files can become corrupted
  org.eclipse.transformer.cli/pom.xml
  org.eclipse.transformer.cli/src/test/java/transformer/test/TestLoad.java
  org.eclipse.transformer.cli/src/test/java/transformer/test/TestTransformServiceConfig.java
  org.eclipse.transformer.cli/src/test/resources/transformer/test/data/complex.properties
  org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ServiceLoaderConfigActionImpl.java
  pom.xml
Labels: bug

#59 58 - Refresh README.md; add INFRA.md, DEV.MD, RULES.md; remove rules.txt
  DEV.md
  INFRA.md
  README.md
  RULES.md
  org.eclipse.transformer/docs/rules.txt
Labels: documentation
